# Generated by Django 4.2.7 on 2023-12-10 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_postcomment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcomment",
            name="post",
        ),
    ]
