# Generated by Django 4.2.7 on 2023-11-30 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
